services:
  - type: web
    name: mysms-api
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0 -p 3000
    envVars:
      - key: RAILS_ENV
        value: production
      - key: MONGODB_URI
